pipeline:
  name: man-flask-k8s-pl
  identifier: manflaskk8spl
  projectIdentifier: Default_Project_1671068007356
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: k8s-deploy
        identifier: k8sdeploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: manflaskk8ssvc
          environment:
            environmentRef: manflaskk8senv
            deployToAll: false
            infrastructureDefinitions:
              - identifier: manflaskk8sinfradef
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
